"""
agents/sql_executor.py — Layer 3: SQL Executor Agent

- Receives validated SQL from erp_planner
- Injects company_id + extracted params
- Runs query against NeonDB PostgreSQL
- Formats results as markdown table or bullet card
- On error: sends back to planner for retry (max 3x)
"""

from __future__ import annotations
from agents.state import OfficeGPTState
from db import run_query, _validate_sql
from datetime import date, datetime
import decimal

MAX_RETRIES = 3


# ── Formatting helpers ────────────────────────────────────────────────────────

def _serialize(val):
    """Convert non-JSON-serializable types to strings."""
    if isinstance(val, (date, datetime)):
        return val.isoformat()
    if isinstance(val, decimal.Decimal):
        return float(val)
    return val


def _normalize_rows(rows: list[dict]) -> list[dict]:
    return [{k: _serialize(v) for k, v in row.items()} for row in rows]


def _format_as_table(rows: list[dict]) -> str:
    """Render list of dicts as a clean markdown table."""
    if not rows:
        return "_No records found._"

    headers = list(rows[0].keys())
    # Pretty-print header names
    pretty = [h.replace("_", " ").title() for h in headers]

    header_row = "| " + " | ".join(pretty) + " |"
    divider    = "| " + " | ".join(["---"] * len(headers)) + " |"
    data_rows  = []
    for row in rows:
        cells = []
        for h in headers:
            val = row.get(h)
            if val is None:
                cells.append("—")
            elif isinstance(val, bool):
                cells.append("✅" if val else "❌")
            else:
                cells.append(str(val))
        data_rows.append("| " + " | ".join(cells) + " |")

    return "\n".join([header_row, divider] + data_rows)


def _format_single_employee(row: dict) -> str:
    """Bullet card for a single employee record."""
    lines = []
    label_map = {
        "first_name":   None,   # merged into name
        "last_name":    None,
        "employee_id":  "🪪 Employee ID",
        "department":   "🏢 Department",
        "designation":  "💼 Designation",
        "joining_date": "📅 Joining Date",
        "email":        "📧 Email",
        "phone":        "📞 Phone",
        "is_active":    "🟢 Status",
        "net_salary":   "💰 Net Salary",
        "salary_month": "📆 Salary Month",
        "status":       "📋 Status",
        "days":         "📅 Days",
        "reason":       "💬 Reason",
    }

    # Name first
    first = row.get("first_name", "")
    last  = row.get("last_name",  "")
    if first or last:
        lines.append(f"**👤 {first} {last}".strip() + "**")

    for key, label in label_map.items():
        if label is None:
            continue
        val = row.get(key)
        if val is None:
            continue
        if key == "is_active":
            val = "Active" if val else "Inactive"
        if key == "net_salary" and val:
            val = f"₹{float(val):,.2f}"
        lines.append(f"{label}: {val}")

    # Any extra fields not in label_map
    known = set(label_map.keys()) | {"first_name", "last_name"}
    for key, val in row.items():
        if key not in known and val is not None:
            label = key.replace("_", " ").title()
            lines.append(f"**{label}:** {val}")

    return "\n".join(lines)


def _format_results(rows: list[dict], question: str) -> str:
    """Choose best format based on result count and question type."""
    count = len(rows)

    if count == 0:
        return "No records found matching your query."

    if count == 1:
        # Single record — bullet card
        return _format_single_employee(rows[0])

    # Multiple records — markdown table
    table = _format_as_table(rows)
    return f"Found **{count} record(s)**:\n\n{table}"


# ── Main executor node ────────────────────────────────────────────────────────

def sql_executor_node(state: OfficeGPTState) -> dict:
    """
    Execute the SQL plan from erp_planner.
    Returns sql_result on success, sql_error on failure (triggers retry).
    """
    sql         = state.get("sql_plan")
    params      = state.get("sql_params", {})
    company_id  = state.get("company_id", 1)
    user_id     = state.get("user_id", None)
    question    = state.get("user_question", "")
    retry_count = state.get("retry_count", 0)

    print(f"[Executor] Running SQL (attempt {retry_count + 1}):", flush=True)
    print(f"[Executor] SQL: {sql}", flush=True)

    if not sql:
        return {
            "sql_error":   "No SQL was generated by the planner.",
            "retry_count": retry_count + 1,
        }

    # Inject company_id and viewer_id (used for employee self-salary queries)
    all_params = {"company_id": company_id}
    if user_id:
        all_params["viewer_id"] = user_id

    try:
        # Safety validation (belt + suspenders)
        _validate_sql(sql)

        rows = run_query(sql, all_params)
        rows = _normalize_rows(rows)

        print(f"[Executor] ✅ Got {len(rows)} rows", flush=True)
        if rows:
            print(f"[Executor] Sample row: {rows[0]}", flush=True)

        formatted = _format_results(rows, question)
        return {
            "sql_result":   rows,
            "final_answer": formatted,
            "sql_error":    None,
            "tool_used":    True,
        }

    except ValueError as ve:
        # SQL safety block — don't retry, fail immediately
        print(f"[Executor] 🚫 Safety block: {ve}", flush=True)
        return {
            "sql_error":    str(ve),
            "final_answer": f"⚠️ {ve}",
            "retry_count":  MAX_RETRIES,  # force stop
            "tool_used":    False,
        }

    except Exception as e:
        error_msg = str(e)
        print(f"[Executor] ❌ SQL error: {error_msg}", flush=True)
        return {
            "sql_error":   error_msg,
            "sql_result":  None,
            "retry_count": retry_count + 1,
            "tool_used":   False,
        }


def route_after_planner(state: OfficeGPTState) -> str:
    """Route after planner — skip executor if access denied."""
    if state.get("access_denied"):
        return "formatter"
    return "sql_executor"


def route_after_executor(state: OfficeGPTState) -> str:
    """
    Conditional edge after sql_executor:
    - Success → formatter (or END if final_answer already set)
    - Error + retries left → back to erp_planner
    - Error + max retries → formatter with error message
    """
    sql_error   = state.get("sql_error")
    retry_count = state.get("retry_count", 0)

    if not sql_error:
        # Success
        intent = state.get("intent", "erp")
        if intent == "hybrid":
            return "rag_agent"   # hybrid: also run RAG
        return "formatter"

    if retry_count < MAX_RETRIES:
        print(f"[Executor] Retrying... ({retry_count}/{MAX_RETRIES})", flush=True)
        return "erp_planner"    # retry with error context

    # Max retries hit
    print("[Executor] Max retries reached — giving up", flush=True)
    return "formatter"